
// POST  https://biblioteca-backend-zmms.onrender.com/usuario

POST http://biblioteca-backend-zmms.onrender.com/usuario
Content-Type: application/json

{
    "registro_academico": "a2558765",
    "nome": "Jose",
    "data_nascimento": "2000-10-10",
    "email": "jose@gmail.com",
    "telefone": "4491234-1234",
    "tipo": "aluno"
}
